### PR TITLE
Fix invalid JSON

### PR DESCRIPTION
**Pull request by roborourke**
Currently composer / wp cli package installs are broken

### CODE REVIEW

**Comment by retlehs** [comment]
:eyes:

**Comment by roborourke** [comment]
Wow I forgot about this one! @retlehs probably worth one of us forking it, last update was 5 years ago. Happy to copy to the Human Made org but I doubt we'll be doing much maintenance ourselves beyond this kind of update in the near future.

**Comment by retlehs** [comment]
:+1: dropped it here earlier: https://github.com/oncarrot/wp-cli-multisite-clone-duplicator

for anyone wanting to quickly install this package (which appears to still be working well! 🙏):

```
wp package install git@github.com:oncarrot/wp-cli-multisite-clone-duplicator.git
```

**Comment by roborourke** [comment]
Thank you!

**Comment by roborourke** [comment]
Closing in favour of fork linked above.

**Pull request closed without merging**
